#  Copyright 2025 United Kingdom Research and Innovation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#   Authored by:    Laura Murgatroyd (UKRI-STFC)


from cil.io import TIFFStackReader
import numpy as np
from cil.framework import AcquisitionData, AcquisitionGeometry
import os


def read_mantid_imaging_data(file_path, pixel_size):
    """
    Reads processed data from TIFF files and a comma-separated angles file.
    Reads the centre of rotation and tilt angle from Mantid Imaging JSON file.
    Parameters
    ----------
    - file_path (str): The path where the TIFF files and angles file are located.
    - pixel_size (float): The pixel size in cm

    Returns
    -------
    - data (cil AcquisitionData): The processed projection data read from the TIFF files.

    Note
    ----
    Assumes data is in Transmission space and converts to Absorption space.
    Assumes file_path contains:
    - image.json : Mantid Imaging JSON file with metadata
    - angles.csv : Comma-separated angles file - this is NOT generated by Mantid Imaging
    - TIFF stack of projections


    """

    # TODO: load pixel size from JSON file

    mi_file = os.path.join(file_path, 'image.json')


    angles_file = os.path.join(file_path, f'angles.csv')

    

    # Read angles from the CSV file
    angles = []
    with open(angles_file, "r") as csvfile:
        for line in csvfile:
            angles.append(float(line.strip()))
    
    # Read projection data using TIFFStackReader
    proj_reader = TIFFStackReader(file_name=file_path)
    data = proj_reader.read()

    import json

    # Read the JSON file
    with open(mi_file, "r") as jsonfile:
        d= json.load(jsonfile)
        # Extract last cor_tilt_finding
        final_cor_tilt = None
        for op in reversed(d["operation_history"]):
            if op["name"] == "cor_tilt_finding":
                final_cor_tilt = op["kwargs"]
                break

    rotation_centre = final_cor_tilt['rotation_centre']
    tilt_angle_deg = final_cor_tilt['tilt_angle_deg']
    
    offset = -rotation_centre + data.shape[2] / 2
    offset = offset + np.tan(tilt_angle_deg * np.pi / 180) * (data.shape[1] / 2)

    acquisition_geometry = AcquisitionGeometry.create_Parallel3D().set_panel(num_pixels=[ data.shape[2], data.shape[1]], pixel_size = [pixel_size, pixel_size]).set_angles(angles=angles)
    ac_data = AcquisitionData(data, geometry=acquisition_geometry)

    ac_data.geometry.set_centre_of_rotation(-offset*pixel_size, angle=-tilt_angle_deg, angle_units='degree')

    from cil.processors import TransmissionAbsorptionConverter
    ac_data = TransmissionAbsorptionConverter()(ac_data)
    return ac_data


def read_angles_from_mi_log_file(file_path, roi=None):
    """
    Reads angles from a Mantid Imaging log CSV file.
    
    Parameters
    ----------
    - file_path (str): The path to the Mantid Imaging log file.
    - roi (tuple): A CIL ROI dict

    Returns
    -------
    - angles (list): The angles read from the log file.

    """


    angles = []
    with open(file_path, "r") as csvfile:
        for line in csvfile:
            if "Projection" in line and "Angle:" in line:
                parts = line.split('Angle:')
                if len(parts) > 1:
                    angle_part = parts[1].split(',')[0].strip()
                    angles.append(float(angle_part))

    if roi is not None and 'angle' in roi:
        start, stop, step = roi['angle']
        angles = angles[start:stop:step]

    return angles